### ISSUE TITLE
AVRO Export to include "namespace"

### ISSUE THREAD

**Issue by gpthome** [datacontract/cli#128]
When "namespace" is added to a datacontract.yaml like...

```
models:
  SampleValue:
    type: table
    namespace: com.sample.schema
    fields:
      customer_no:
        type: string
        required: true
      acquired_dt:
        type: long
        required: true
```

and this command is executed, `datacontract export --model SampleValue --format avro `, the "namespace" is missing from the output.  

```
{
  "type": "record",
  "name": "SampleValue",
  "namespace": "com.sample.schema",   <= MISSING
  "fields": [
    {
      "name": "customer_no",
      "type": "string"
    },
    {
      "name": "acquired_dt",
      "type": "long"
    }
  ]
}
```

The namespace is used by Java code generators.  The namespace is turned in the Java class package.

_Originally posted by @gpthome in https://github.com/datacontract/cli/issues/121#issuecomment-2030899735_
