### ISSUE TITLE
Great-Expectations Export: Support quality definition stored in a json file

### ISSUE THREAD

**Issue by saugerDecathlon** [datacontract/cli#136]
```
quality:
  type: great-expectations
  specification:
    orders: "$ref: ./examples/great-expectations/quality.json"
```
