### ISSUE TITLE
export --format dbt

### ISSUE THREAD

**Issue by simonharrer** [datacontract/cli#37]
This issue is about exporting a data contract to the dbt format.

**Comment by adaminsta** [comment]
What is the status on DBT export? @simonharrer. My team use DBT+Snowflake are looking into a few alternatives for data contract implementations like this cli, paypal etc

**Comment by simonharrer** [comment]
@adaminsta I've started with https://github.com/datacontract/cli/pull/38 and want to release a first version of the dbt export on Friday afternoon.

Would love your thoughts and ideas on the dbt export. Any expectations already in your mind?

**Comment by adaminsta** [comment]
We want to build a dbt model (in Snowflake) on top of the contract. From the datacontract we want a dbt source, dbt schema (with an owner, contract, etc), and the staging model

**Comment by simonharrer** [comment]
We currently have the following export behaviour implemented in the draft PR:

datacontract.yaml
```
dataContractSpecification: 0.9.2
id: orders-unit-test
info:
  title: Orders Unit Test
  version: 1.0.0
models:
  orders:
    fields:
      order_id:
        type: varchar
        unique: true
        required: true
      order_total:
        type: bigint
        required: true
```

datacontract export --format dbt datacontract.yaml
```
version: 2
models:
  - name: orders    
    config:
      materialized: table
      contract:
        enforced: true
    columns:
      - name: order_id
        data_type: text
        constraints:
          - type: not_null
          - type: unique
      - name: order_total
        data_type: integer
        constraints:
          - type: not_null    
```

**Comment by simonharrer** [comment]
Just merged a first implementation of the dbt export. It currently has only a mapping for snowflake but already supports all fields in the model. Does this already help you? What is missing for you @adaminsta ?

**Comment by adaminsta** [comment]
Our idea is to use this tool to automatically create the resources and tables/models needed with CI/CD, based on the contract.

Getting the dbt schema is very useful. To make it even more powerful:
1) Generate a dbt source with the model name as table, based on the snowflake database and schema 
e.g:
```
models:
  - name: orders    
    config:
      materialized: table
      contract:
        enforced: true
    columns:
      - name: order_id
        data_type: text
        constraints:
          - type: not_null
          - type: unique
[...]
servers:
  endpoint:
    type: snowflake
    account: xx0000
    database: MY_DB
    schema: MY_SCHEMA
```
provides 

```
sources:
  - name: contract_name
    database: my_db  
    schema: my_schema  
    tables:
      - name: orders
```

2) Generate a staging model 
In our automation process we'd also like to push a PR to our DBT repo in order to remove the bottle of the data engineer.
Therefore, it would be useful to also generate a staging model that selects all columns from the source. 

```
{{ config(
    materialized="table"
) }}

select 
    order_id
    [...]
from {{ source('contract_name', 'orders')}}
```
