### ISSUE TITLE
Add pubsub as an option for server 

### ISSUE THREAD

**Issue by adaminsta** [datacontract/cli#58]
We are consuming data from a pub-sub topic and putting it into snowflake, but there is no pubsub option for servers. Need something like this:

```
source:
  type: pubsub
  project: gcp_project_name
  name: my_topic
 endpoint:
    type: snowflake
    account: xxxxxxxx
    database: my_db
    schema: my_schema
```
