### ISSUE TITLE
Is Schema Object still supported?

### ISSUE THREAD

**Issue by rae89** [datacontract/cli#66]
Is the Schema Object in the datacontract specification still supported?  https://github.com/datacontract/datacontract-specification/?tab=readme-ov-file#schema-object

I am trying to define a jsonschema for a particular data contract by using the Schema Object. Like so:

```yaml
dataContractSpecification: 0.9.2
id: urn:datacontract:checkout:orders-latest
info:
  title: Orders Latest
  version: 1.0.0
schema:
  type: json-schema
  specification:
    orders:
      description: One record per order. Includes cancelled and deleted orders.
      type: object
      properties:
        order_id:
          type: string
          description: Primary key of the orders table
        order_timestamp:
          type: string
          format: date-time
          description: The business timestamp in UTC when the order was successfully registered in the source system and the payment was successful.
        order_total:
          type: integer
          description: Total amount of the order in the smallest monetary unit (e.g., cents).
    line_items:
      type: object
      properties:
        lines_item_id:
          type: string
          description: Primary key of the lines_item_id table
        order_id:
          type: string
          description: Foreign key to the orders table
        sku:
          type: string
          description: The purchased article number
```

and run the following cli command: 

```bash
datacontract export --format jsonschema orders.yml
```

But this does not work.  I get the following error:

```bash
─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /Users/robert/Projects/data_contracts/env/lib/python3.11/site-packages/datacontract/cli.py:133   │
│ in export                                                                                        │
│                                                                                                  │
│   130 │   Convert data contract to a specific format. Prints to stdout.                          │
│   131 │   """                                                                                    │
│   132 │   # TODO exception handling                                                              │
│ ❱ 133 │   result = DataContract(data_contract_file=location).export(format)                      │
│   134 │   print(result)                                                                          │
│   135                                                                                            │
│   136                                                                                            │
│                                                                                                  │
│ ╭────────────────────── locals ──────────────────────╮                                           │
│ │   format = <ExportFormat.jsonschema: 'jsonschema'> │                                           │
│ │ location = 'orders.yml'                            │                                           │
│ ╰────────────────────────────────────────────────────╯                                           │
│                                                                                                  │
│ /Users/robert/Projects/data_contracts/env/lib/python3.11/site-packages/datacontract/data_contrac │
│ t.py:152 in export                                                                               │
│                                                                                                  │
│   149 │   │   data_contract = resolve.resolve_data_contract(self._data_contract_file, self._da   │
│   150 │   │   │   │   │   │   │   │   │   │   │   │   │     self._data_contract)                 │
│   151 │   │   if export_format == "jsonschema":                                                  │
│ ❱ 152 │   │   │   model_name, model = next(iter(data_contract.models.items()))                   │
│   153 │   │   │   jsonschema_dict = to_jsonschema(model_name, model)                             │
│   154 │   │   │   return json.dumps(jsonschema_dict, indent=2)                                   │
│   155 │   │   if export_format == "sodacl":                                                      │
│                                                                                                  │
│ ╭──────────────────────────────────── locals ─────────────────────────────────────╮              │
│ │ data_contract = DataContractSpecification(                                      │              │
│ │                 │   dataContractSpecification='0.9.2',                          │              │
│ │                 │   id='urn:datacontract:checkout:orders-latest',               │              │
│ │                 │   info=Info(                                                  │              │
│ │                 │   │   title='Orders Latest',                                  │              │
│ │                 │   │   version='1.0.0',                                        │              │
│ │                 │   │   description=None,                                       │              │
│ │                 │   │   owner=None,                                             │              │
│ │                 │   │   contact=None                                            │              │
│ │                 │   ),                                                          │              │
│ │                 │   servers={},                                                 │              │
│ │                 │   terms=None,                                                 │              │
│ │                 │   models={},                                                  │              │
│ │                 │   examples=[],                                                │              │
│ │                 │   quality=None                                                │              │
│ │                 )                                                               │              │
│ │ export_format = <ExportFormat.jsonschema: 'jsonschema'>                         │              │
│ │          self = <datacontract.data_contract.DataContract object at 0x11357d850> │              │
│ ╰─────────────────────────────────────────────────────────────────────────────────╯              │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
StopIteration
```

If I specify the Model Object similar to the  examples in the docs it will work, but I want to control adding the jsonschema definition using the Schema Object.  Is this even possible?
