### ISSUE TITLE
Array type support in avro import

### ISSUE THREAD

**Issue by ismailova-n** [datacontract/cli#94]
Arrays need to be treated similarly to records, in `import_record_fields`, with `imported_fields[field_name].items = import_record_fields(field.items)`.

_Originally posted by @jeeger in https://github.com/datacontract/cli/pull/88#discussion_r1524358748_

**Comment by simonharrer** [comment]
Example for array in data contract

```yaml
dataContractSpecification: 0.9.3
id: urn:datacontract:orders-latest
info:
  title: Orders Latest
  version: 1.0.0
models:
  orders:
    type: table
    fields:
      order_id:
        type: text
        primary: true
        required: true
        pattern: ^B.*$
        maxLength: 10
      email_adresses:
        type: array
        description: Different email adresses of a customer
        items:
           type: text
           format: email
           pattern: ^.*@.*$
```
