### ISSUE TITLE
Camel case in `datacontract.yaml` not supported

### ISSUE THREAD

**Issue by pamo-dmg** [datacontract/cli#97]
When testing the CLI (`v0.9.7`) and running the command `datacontract test`, I got the following failure:

```
$ datacontract test 
Testing datacontract.yaml
Column,Event,Details
fooField,:icon-fail: Required Column Missing, 

Required Column Missing,
Column,Event,Details
fooField,:icon-fail: Required Column Missing, 

Required Column Missing,
Column,Event,Details
barField,:icon-fail: Required Column Missing, 

Required Column Missing,
Column,Event,Details
barField,:icon-fail: Required Column Missing, 

Required Column Missing,
╭────────┬───────────────────────────────────────────────────────┬──────────┬──────────────────────────╮
│ Result │ Check                                                 │ Field    │ Details                  │
├────────┼───────────────────────────────────────────────────────┼──────────┼──────────────────────────┤
│ failed │ Check that field fooField is present                  │          │ Required Column Missing, │
│ failed │ Check that field fooField has type text               │          │ Required Column Missing, │
│ failed │ Check that field barField is present                  │          │ Required Column Missing, │
│ failed │ Check that field barField has type text               │          │ Required Column Missing, │
│ passed │ Check that required field fooField has no null values │ fooField │                          │
│ passed │ Check that required field barField has no null values │ barField │                          │
╰────────┴───────────────────────────────────────────────────────┴──────────┴──────────────────────────╯
🔴 data contract is invalid, found the following errors:
1) Required Column Missing,
1) Required Column Missing,
1) Required Column Missing,
1) Required Column Missing,
```

I couldn't find out why this was the case. Therefore, I checked the database colums of my postgresDB and my `datacontract.yaml`, if they are missmatching. 

```sql
create table example (
  foofield text not null,
  barfiled text not null,
  primary key (foofield, barfiled)
);

```

```yaml
dataContractSpecification: 0.9.3
id: test-id
info:
  title: test foo bar
  version: 0.0.1
  description: My description
  owner: TeamXYZ
  contact:
    name: Max Mustermann (Product Owner)
    email: max@mustermann.de

servers:
  dev:
    type: postgres
    host: localhost
    port: 5432
    database: postgres
    schema: public


models:
  example:
    description: Some example description
    type: table
    fields:
      fooField:
        description: This is the foo field
        required: true
        type: text
      barField:
        description: This is the bar field
        required: true
        type: text
``` 

But both looked good to me. After some trial and error, I discovered that the columns of my table are not recognized if the "model" fields are defined in camel-case in the YAML file. As the top field `dataContractSpecification`, which is created by the `init` command, is defined in camel-case, I expected the whole YAML to be supported with camel-case.

I work with the following `model` definition:
```yaml
models:
  example:
    description: Some example description
    type: table
    fields:
      foofield:
        ...
      barfield:
        ...
```

Do you plan to support camel-case from the YAML? And if not, could you maybe add some hints when using the command `lint´?
